name: Node.js CI/CD

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run Jest tests
      run: npm test

    - name: Deploy to EC2 instance
      run: |
        ssh -i deploy-auto/src/Testing-Instance_Staging-Instance.pem ubuntu@ec2-3-106-222-162.ap-southeast-2.compute.amazonaws.com 'cd devops-auto && git pull && npm install && npm run build && pm2 restart app'
